### ISSUE TITLE
"Invalid - HotfixInstallationInfo.xml could not be found or is invalid" after importing build made by FSCM 

### ISSUE THREAD

**Issue by jofme** [ameyer505/D365FOAdminToolkit#51]
I'm unable to import the packages generated by the build action using LCS.
Builds generated by VS works fine.

Is there an issue with LCS?

![image](https://github.com/user-attachments/assets/1e17d376-27bc-4037-a9ef-d4b8ca6561d2)

**Comment by FH-Inway** [comment]
This is caused by an odd behavior on how GitHub uploads artifacts. Even if the artifact is already a .zip file, the [upload-artifact](https://github.com/actions/upload-artifact#zipped-artifact-downloads) action wraps it into another .zip file. So you first need to unpack the .zip file downloaded from the build action. And then upload the .zip file inside that to LCS.

I will take a look into changing this so that the downloaded .zip file is already the .zip file that can be uploaded to LCS.

**Comment by jofme** [comment]
Okay, didn't think of it. Thanks!

**Comment by FH-Inway** [comment]
#52 should do the trick, see https://github.com/ameyer505/D365FOAdminToolkit/actions/runs/12123869028?pr=52
Also created https://github.com/jofme/D365FinanceToolbox/pull/64 for the finance toolbox.

**Comment by jofme** [comment]
Works now. Thanks!
I'll approve the PR in Finance Toolbox.

<img width="768" alt="image" src="https://github.com/user-attachments/assets/d0f4f5d0-9710-4fea-9d4b-841dcb2a1940">
